In [1]:
import tensorflow as tf

tf.enable_eager_execution()

In [3]:
layer = tf.keras.layers.Dense(100)
layer = tf.keras.layers.Dense(10, input_shape=[None, 5])

In [5]:
layer(tf.zeros([10, 5]))

<tf.Tensor: id=29, shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [12]:
layer.variables

[<tf.Variable 'dense_2/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.03483725,  0.61271137,  0.580028  ,  0.07697695, -0.4123034 ,
          0.36209208,  0.31228536,  0.4094798 ,  0.18082196,  0.5718556 ],
        [-0.5551927 ,  0.21244967, -0.342985  ,  0.31153202, -0.16785878,
         -0.12351698, -0.60821605,  0.5551556 , -0.56729484, -0.2162995 ],
        [-0.49446338,  0.619646  , -0.18027776, -0.3772479 , -0.1926642 ,
         -0.31843245, -0.2702339 ,  0.4604736 , -0.36457318,  0.16163963],
        [-0.6021861 ,  0.24956554,  0.04330289, -0.5037081 , -0.26863387,
          0.18199301,  0.06734198, -0.61553967,  0.52160555,  0.2801444 ],
        [ 0.16786754, -0.09484804,  0.14174193, -0.06338286, -0.55658716,
          0.46254915, -0.24560747,  0.5686886 ,  0.286017  ,  0.14462548]],
       dtype=float32)>,
 <tf.Variable 'dense_2/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [13]:
layer.trainable_variables

[<tf.Variable 'dense_2/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.03483725,  0.61271137,  0.580028  ,  0.07697695, -0.4123034 ,
          0.36209208,  0.31228536,  0.4094798 ,  0.18082196,  0.5718556 ],
        [-0.5551927 ,  0.21244967, -0.342985  ,  0.31153202, -0.16785878,
         -0.12351698, -0.60821605,  0.5551556 , -0.56729484, -0.2162995 ],
        [-0.49446338,  0.619646  , -0.18027776, -0.3772479 , -0.1926642 ,
         -0.31843245, -0.2702339 ,  0.4604736 , -0.36457318,  0.16163963],
        [-0.6021861 ,  0.24956554,  0.04330289, -0.5037081 , -0.26863387,
          0.18199301,  0.06734198, -0.61553967,  0.52160555,  0.2801444 ],
        [ 0.16786754, -0.09484804,  0.14174193, -0.06338286, -0.55658716,
          0.46254915, -0.24560747,  0.5686886 ,  0.286017  ,  0.14462548]],
       dtype=float32)>,
 <tf.Variable 'dense_2/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [16]:
layer.kernel, layer.bias

(<tf.Variable 'dense_2/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.03483725,  0.61271137,  0.580028  ,  0.07697695, -0.4123034 ,
          0.36209208,  0.31228536,  0.4094798 ,  0.18082196,  0.5718556 ],
        [-0.5551927 ,  0.21244967, -0.342985  ,  0.31153202, -0.16785878,
         -0.12351698, -0.60821605,  0.5551556 , -0.56729484, -0.2162995 ],
        [-0.49446338,  0.619646  , -0.18027776, -0.3772479 , -0.1926642 ,
         -0.31843245, -0.2702339 ,  0.4604736 , -0.36457318,  0.16163963],
        [-0.6021861 ,  0.24956554,  0.04330289, -0.5037081 , -0.26863387,
          0.18199301,  0.06734198, -0.61553967,  0.52160555,  0.2801444 ],
        [ 0.16786754, -0.09484804,  0.14174193, -0.06338286, -0.55658716,
          0.46254915, -0.24560747,  0.5686886 ,  0.286017  ,  0.14462548]],
       dtype=float32)>,
 <tf.Variable 'dense_2/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>)

In [17]:
class MyDenseLayer(tf.keras.layers.Layer):
    def __init__(self, num_outputs):
        super(MyDenseLayer, self).__init__()
        self.num_outputs = num_outputs

    def build(self, input_shape):
        self.kernel = self.add_variable("kernel",
                                        shape=[int(input_shape[-1]),
                                               self.num_outputs])

    def call(self, input):
        return tf.matmul(input, self.kernel)

layer = MyDenseLayer(10)
print(layer(tf.zeros([10, 5])))
print(layer.trainable_variables)

tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(10, 10), dtype=float32)
[<tf.Variable 'my_dense_layer/kernel:0' shape=(5, 10) dtype=float32, numpy=
array([[ 0.0265677 , -0.10860211,  0.41798574,  0.26343995, -0.23080781,
        -0.39200562, -0.5716988 ,  0.44250542, -0.00926858, -0.45217246],
       [-0.2732895 ,  0.15663874,  0.29661703,  0.60487527,  0.42247897,
        -0.22741568, -0.41398424,  0.30559248, -0.39145526,  0.52986985],
       [-0.34043968, -0.3957618 , -0.62664354,  0.1295802 ,  0.21069497,
         0.10918188,  0.47660822, -0.57499564, -0.10601866,  0.32700765],
       [ 0.19498652,  0.6288274 ,  0.52534956, -0.25378433, -0.5059089 ,
        -0.16707572,  0.33292025, -0

In [18]:
class ResnetIdentityBlock(tf.keras.Model):
    def __init__(self, kernel_size, filters):
        super(ResnetIdentityBlock, self).__init__(name='')
        filters1, filters2, filters3 = filters

        self.conv2a = tf.keras.layers.Conv2D(filters1, (1, 1))
        self.bn2a = tf.keras.layers.BatchNormalization()

        self.conv2b = tf.keras.layers.Conv2D(filters2, kernel_size, padding='same')
        self.bn2b = tf.keras.layers.BatchNormalization()

        self.conv2c = tf.keras.layers.Conv2D(filters3, (1, 1))
        self.bn2c = tf.keras.layers.BatchNormalization()

    def call(self, input_tensor, training=False):
        x = self.conv2a(input_tensor)
        x = self.bn2a(x, training=training)
        x = tf.nn.relu(x)

        x = self.conv2b(x)
        x = self.bn2b(x, training=training)
        x = tf.nn.relu(x)

        x = self.conv2c(x)
        x = self.bn2c(x, training=training)

        x += input_tensor
        return tf.nn.relu(x)


block = ResnetIdentityBlock(1, [1, 2, 3])
print(block(tf.zeros([1, 2, 3, 3])))
print([x.name for x in block.trainable_variables])

Instructions for updating:
Colocations handled automatically by placer.
tf.Tensor(
[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]], shape=(1, 2, 3, 3), dtype=float32)
['resnet_identity_block/conv2d/kernel:0', 'resnet_identity_block/conv2d/bias:0', 'resnet_identity_block/batch_normalization_v1/gamma:0', 'resnet_identity_block/batch_normalization_v1/beta:0', 'resnet_identity_block/conv2d_1/kernel:0', 'resnet_identity_block/conv2d_1/bias:0', 'resnet_identity_block/batch_normalization_v1_1/gamma:0', 'resnet_identity_block/batch_normalization_v1_1/beta:0', 'resnet_identity_block/conv2d_2/kernel:0', 'resnet_identity_block/conv2d_2/bias:0', 'resnet_identity_block/batch_normalization_v1_2/gamma:0', 'resnet_identity_block/batch_normalization_v1_2/beta:0']


In [19]:
my_seq = tf.keras.Sequential([tf.keras.layers.Conv2D(1, (1, 1)),
                              tf.keras.layers.BatchNormalization(),
                              tf.keras.layers.Conv2D(2, 1, padding='same'),
                              tf.keras.layers.BatchNormalization(),
                              tf.keras.layers.Conv2D(3, (1, 1)),
                              tf.keras.layers.BatchNormalization()])
my_seq(tf.zeros([1, 2, 3, 3]))

<tf.Tensor: id=547, shape=(1, 2, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>